CREATE TABLE events
(
    event_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                      VARCHAR(100),
    date                      date,
    available_attendees_count INT check (available_attendees_count between 1 and 1000),
    description               VARCHAR(500),
    category                  VARCHAR(255),
    CONSTRAINT pk_events PRIMARY KEY (event_id)
);

CREATE TABLE tickets
(
    ticket_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attendance_count INT,
    user_id          BIGINT,
    event_id         BIGINT,
    CONSTRAINT pk_reservations PRIMARY KEY (ticket_id)
);

CREATE TABLE users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(100),
    password VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE audits
(
    audit_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    audit_date TIMESTAMP,
    message    VARCHAR(255),
    CONSTRAINT pk_audits PRIMARY KEY (audit_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (event_id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);